### ISSUE TITLE
Variable softActivated and softFields scope

### ISSUE THREAD

**Issue by vangoz** [lanetix/node-bookshelf-soft-delete#22] opened 2015-11-18 06:10 UTC
I see that those variables are outside the extended model, is that how it's supposed to be? Because this way if I apply `soft: true` to 1 model then the other models will also have soft delete even if I don't apply `soft: true`.
I want to submit pull request but it fails the mocha test on "should be visible in model count with no column argument and softDelete: false:" because it returns 0 instead of 3. I haven't read the mocha test in detail but why should it be 3 instead of 0? Do I have wrong assumption about this library?

**Comment by apechimp** [comment] 2015-11-19 18:26
I'm not quite sure I follow. Go ahead and submit the PR even though the tests are failing. I think that'll give the discussion a little more context.

**Comment by vangoz** [comment] 2015-11-20 04:38
About the test case on "should be visible in model count with no column argument and softDelete: false:" I don't get why it should be 3. From what I understand Model4 has no "soft" attribute so the rows should have been deleted for real.
I'll submit a pull request.

**Comment by apechimp** [comment] 2015-11-23 20:24
This appears to have been caused by #17 which made `softActivated` global. I want to figure out if using something like `this._soft` instead of `this.soft` will work for the use case #17 addressed before proceeding.

**Comment by juliusza** [comment] 2016-01-21 13:27
+1, these variables should belong to model

**Comment by juliusza** [comment] 2016-01-29 09:12
Fixed in version 4.0.0

d16bb0d1919cb6c603d048e97020b2d8aede9720

**Closed by juliusza** 2016-01-29 09:12 UTC
